name: run-tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run the test
        run: |
          yarn
          yarn build
          yarn test
